### ISSUE TITLE
有关test.py有点问题想请教一下

### ISSUE THREAD

**Issue by tizikaoroubanfan** [windrunners/TUFusion#2]
请问您的test测试数据集是用的imagefusion-nestfuse （https://github.com/hli1221/imagefusion-nestfuse）里面的测试集吗？我跑了一下跑不通，出现了RuntimeError_ Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor)

**Comment by windrunners** [comment]
应该不是测试集的问题，所有的测试集图像都是适用的。看看是否是模型加载或者环境配置有问题？

**Comment by tizikaoroubanfan** [comment]
好的好的，谢谢您

**Comment by 1354555126** [comment]
您好有关train_tufusion.py,以及test.py,有点问题想请教一下再运行train_tufusion.py时报错RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same。在用博主的权重文件跑test.py时报Input type （torch.FloatTensor） 和权重类型 （torch.cuda.FloatTensor）试了很多种方法还是没办法，请问有什么方法解决吗？目前cpu跑是没问题的

**Comment by 1354555126** [comment]
> 好的好的，谢谢您
麻烦问下，您解决了这个问题了吗？

**Comment by windrunners** [comment]
一种方式：
重点看下torch.load这条，改为torch.load('xxx', map_location=lambda storage, loc: storage.cuda)
 
另外一种方式：
权重删除，重新训练

**Comment by 1354555126** [comment]
好的，我试试，谢谢您

**Comment by 1354555126** [comment]
博主您好，昨天的问题大概解决了但是又有一个新的问题AttributeError: 'Conv2d' object has no attribute 'size'，好像是output和x的维度不一样，一个是Conv2d(16, 1, kernel_size=(1, 1), stride=(1, 1))一个是（4 1 256 256 ）

**Comment by 1354555126** [comment]
补充一下，这个是在训练过程中出现的问题

**Comment by windrunners** [comment]
CUDA或者GPU环境下，可能会报错：Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same。

解决办法如下：

测试时，将test,image.py中第24行“TUFusion_model.to(device)”删掉或注释掉。
训练时，问题不大，但也要适当调整下。
